export const theme = {
    BAR_STYLE: 'dark-content',
    BAR_BACKGROUND_COLOR: 'transparent',
    INITIAL_BORDER: 24,
    FONT_SIZE_VENTI: 28,
    FONT_SIZE_LARGE: 24,
    FONT_SIZE_MEDIUM: 20,
    FONT_SIZE_SMALL: 14,
    FONT_FAMILY: 'LeagueSpartan-Regular',
    BACKGROUND_COLOR: '#e5ddc8',
    PRIMARY_COLOR: '#4a4a4a',
    BORDER_COLOR: '#dfe0e2',
    ALERT_COLOR: '#db1f48',
    LIGHT_COLOR: '#fff',
    PALLETE01_COLOR: '#e5ddc8',
    PALLETE02_COLOR: '#01949a',
    PALLETE03_COLOR: '#004369',
    PALLETE04_COLOR: '#db1f48',
};
